---
default_config:

frontend:
  themes: !include_dir_merge_named "themes"

automation ui: !include "automations.yaml"

lovelace:
  mode: "storage"

logger:
  default: "info"
  logs:
    custom_components.ui_lovelace_minimalist: "debug"

browser_mod:
virtual:

weather:
  - platform: "template"
    name: "DummyTown"
    condition_template: "cloudy"
    temperature_template: "{{ '20' | float }}"
    humidity_template: "{{ '50' | float }}"

light:
  - platform: "virtual"
    name: "Livingroom"
    support_color: true
    support_color_temp: true
    support_white_value: true

sensor:
  - platform: "time_date"
  - platform: "virtual"
    name: "Livingroom Temperature"
    class: "temperature"
    initial_value: 20
    initial_availability: true
  - platform: "virtual"
    name: "Livingroom Humidity"
    class: "humidity"
    initial_value: 50
    initial_availability: true
