---
# https://www.home-assistant.io/integrations/default_config/
default_config:

frontend:
  themes: !include_dir_merge_named "themes"

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: "info"
  logs:
    custom_components.ui_lovelace_minimalist: "debug"
  filters:
    homeassistant.components.go2rtc:
      - "Could not find go2rtc docker binary"
    homeassistant.setup:
      - ".*go2rtc.*"

# Example of a template sensor
template:
  - sensor:
      - name: "Current Date and Time"
        unique_id: "current_date_time_sensor"
        state: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
        icon: "mdi:calendar-clock"
